// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjeaxjdujzdrlkkfdzjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZWF4amR1anpkcmxra2ZkempjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NzgwNzUsImV4cCI6MjA1OTE1NDA3NX0.ubDz6bILvK5FDpSLCquFrgMvuQt8sOw28LCdmjCVFpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);